### ISSUE TITLE
If a row is deleted while an item on another is edited, editor retains position

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#13]
1. Inline edit some property at the demo
2. Remove a row on top of it -> The editor retains it's position. Instead it should follow the row it belongs to.

Another problem is that edited cells still remain open and retain their data if you change a page (ie. open a few inline editors and hit another page). This happens because `rowIndex` points at index local to the given page.

Maybe there's some clean way to sidestep these problems. Maybe we need to drop the concept of `editedCells` and replace it something else. Especially the first problem is a nasty one since it implies syncing is required in case multiple structures are used.

@eviltoylet Ideas are welcome.

**Comment by eviltoylet** [comment]
Well, the good thing is that I believe these issues are specific to the demo implementation. :) Unfortunately, some parts are still tightly coupled to the library since the abstraction for cell editors isn't crisp enough.

>1. Inline edit some property at the demo
>2. Remove a row on top of it -> The editor retains it's position. Instead it should follow the row it belongs to.

There's a lot of little issues here: 
- The remove should really take care of modifying the content of `editedCells`. However, `editedCells` are an internal implementation of `edit.jsx.`
- Root problem is that cells are used as views on a row/column within the code but they're logically treated as stateful elements.

>Another problem is that edited cells still remain open and retain their data if you change a page (ie. open a few inline editors and hit another page). 

This is due to the fact that the paginator (and search) removes `Table`'s knowledge about where the data lives globally.

> Maybe there's some clean way to sidestep these problems. Maybe we need to drop the concept of `editedCells` and replace it something else.

In general, I think the `Table` needs a way to dispatch events which indicate what happened. (row added, row removed, column edited) and just have appropriate handlers for them. There are also some tricky edge cases... for example:
- table sorted by column A
- column A is edited for a row and saved
  - should that row be sorted? (logically correct)
  - or should that row remain in place? (makes it easier for user to edit)

I can flesh out a solution if you'd like.

On the flip side, allowing edit of only one cell at a time, and disabling all navigation controls is also a legitimate way to go :)

**Comment by bebraw** [comment]
Thanks for your extensive comment!

> In general, I think the Table needs a way to dispatch events which indicate what happened. (row added, row removed, column edited) and just have appropriate handlers for them. There are also some tricky edge cases... for example:

Yeah, that sounds like a good idea! I'll think about this and implement some sort of API.

> On the flip side, allowing edit of only one cell at a time, and disabling all navigation controls is also a legitimate way to go :)

Absolutely. Given it is just a demo, better not to make it too complex.

I think a lot of the current issues could be simplified by implementing some variant of Flux pattern. In terms of Reflux it would make sense to push basic table operations as Actions. In addition there would be a Store that would deal with pagination and visible data concerns. This would make it considerably easier to deal with multiple inline editors and such given you have the right data at the right place.

That said maybe the whole `editedCells` thing needs to go away from the default implementation. As you mentioned, there's some sort of impedance mismatch here.

In fact this could make an excellent another demo. I guess that's something I should do for the next release as well. That will help in improving the design.

Again, thanks a lot! :)

**Comment by eviltoylet** [comment]
Any idea when you'll get around to implementing this? :)

**Comment by bebraw** [comment]
I'll spend some time on this tomorrow. :)

**Comment by bebraw** [comment]
@eviltoylet I think I know how to solve the editor/page conflict. If you look closely, you can see dropdown and boolean get their state correctly based on page data. The only problem is that input seems to have internal state. If we can figure out a nice way to eliminate that, then this would work nicely. I have a feeling there might be some life cycle method just for this purpose (need to override input state when value property changes).

**Comment by bebraw** [comment]
This is actually an issue still but just for input. I guess we'll need to tweak the implementation of the text editor to take prop changes in count correctly. That should fix it.
