### ISSUE TITLE
Inline editing confusing

### ISSUE THREAD

**Issue by Tjorriemorrie** [bebraw/reactabular#74]
Is there a working example for the inline editing? I can't get it to work and the documentation doesn't help to explain it at all to a newcomer to react. Where do I do my update to the backend, etc.

**Comment by bebraw** [comment]
Hi,

If you look at the `full_table` demo, you'll find a snippet like:

```javascript
var editable = cells.edit.bind(this, 'editedCell', (value, celldata, rowIndex, property) => {
    var idx = findIndex(this.state.data, {
        id: celldata[rowIndex].id,
    });

    this.state.data[idx][property] = value;

    this.setState({
        data: data,
    });
});
```

The example operates based on local data. When you have a backend in place, you would trigger your action updating backend here instead of doing `this.setState`. This assumes you have Flux or similar architecture.

Each part of Reactabular that operates with local data would have to be patched like this. There are enough hooks for that and I've actually done work against a backend at [react-crm-frontend](https://github.com/bebraw/react-crm-frontend) if you want another example. There's no inline edit in this example, though.

**Comment by eviltoylet** [comment]
@Tjorriemorrie did bebraws explanation help? Maybe we can add a redacted version of that in to the documentation for those getting acquainted to the technology stack.
